apiVersion: v1
kind: Service
metadata:
  name: nodejs-trpc
  namespace: nodejs-trpc
  labels:
    app: nodejs-trpc
spec:
  type: ClusterIP
  selector:
    app: nodejs-trpc
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
